#! /bin/bash

if [ $# != 2 ]; then
    echo "functie: cenverteert een audiobestand naar een ander type"
    echo "syntax: ./opdr1 wav mp3"
    echo "kan wav en aiff naar mp3, flac of converteren"
else
    oldExt=$1
    newExt=$2

    if ([ $oldExt == "wav" ] || [ $oldExt == "aiff" ]); then

        path="`pwd`/new_${newExt}_files"

        echo "van plan de nieuwe $newExt files te plaatsen in:"
        echo ${path}
        echo "is dit oke? (y/n)"
        read answer

        if [ $answer == "y" ]; then
            if [ ! -d "${path}" ]; then
                mkdir "${path}"
            fi
            for file in *$oldExt; do
                echo "bezig met: ${file}"
                newFile="`basename "${file}" .$oldExt`"
                if [ $newExt == "mp3" ]; then
                    lame -V2 "${file}" "${path}/${newFile}.flac"
                elif [ $newExt == "flac" ]; then
                    echo "supergafe naar flac converter ${file} ${path}/${newFile}.mp3"
                else
                    echo "kan alleen wav of aiff files naar map3 of flac converteren"
                fi
            done
            echo "klaar met converteren, nieuwe files geplaats in:"
            echo ${path}
        else
            echo "$answer beantwoord, proces beeindigen"
        fi
    else
        echo "kan alleen wav of aiff files naar map3 of flac converteren"
    fi
fi
